### ISSUE TITLE
Diaphone with screws missing ring

### ISSUE THREAD

**Issue by J-Svejk** [benjaminwand/3d-printed-diaphone-pipe#1]
It might be me looking at the files incorrectly, but I can't find the ring that retains the rubber diaphragm for the diaphone with screws.

**Comment by benjaminwand** [comment]
The smaller ring is inside the larger ring. Can you see it now?

**Comment by J-Svejk** [comment]
Hello;

I was after the outer part.  It was not showing because it is commented out in the code. Once I removed the /* the part appeared.

Thank you.  Can’t wait to try it!

Best Regards,
Dave

Sent from my iPhone

On Jun 25, 2019, at 12:45 AM, Benjamin Wand <notifications@github.com> wrote:

The smaller ring is inside the larger ring. Can you see it now?

**Comment by benjaminwand** [comment]
Oh I see, thanks for telling me!
